version: '3.15'

name: meetup-api
services:
  server:
    build: ../
    restart: on-failure
    container_name: m-a-server
    hostname: ${APP_HOSTNAME}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOSTNAME}:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_FLYWAY_URL=jdbc:postgresql://${POSTGRES_HOSTNAME}:5432/${POSTGRES_DB}
      - SPRING_FLYWAY_USER=${POSTGRES_USER}
      - SPRING_FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database
    ports:
      - ${APP_PORT}:8080

  database:
    image: postgres:latest
    restart: always
    container_name: m-a-database
    hostname: ${POSTGRES_HOSTNAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432